security:
    encoders:
<<<<<<< HEAD
        Kikala\FrontBundle\Entity\UserKikologue: 
            algorithm: sha512
=======
        Symfony\Component\Security\Core\User\User:
            algorithm:  sha512
            iterations: 1
            encode_as_base64: false
>>>>>>> 5d1736c9e7b48b305eb76008df4b6feea62d494d

    role_hierarchy:
        ROLE_USER:        ROLE_BASIC
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
         entity: { class: KikalaFrontBundle:Userkikologue, property: pseudo }


    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }