security:
    encoders:
        Kikala\FrontBundle\Entity\UserKikologue: 
            algorithm: sha512
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
         entity: { class: KikalaFrontBundle:UserKikologue, property: pseudo }


    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path: /redirect/
            logout:
                path:   /logout
                target: /home/
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http}
        - { path: ^/kikologue/, roles: ROLE_USER, requires_channel: http }
        - { path: ^/formaIns/, roles: ROLE_USER, requires_channel: http }