kikala_front_homepage:
    path:     /home/
    defaults: { _controller: KikalaFrontBundle:Default:home }

kikala_front_legal:
    path:     /legal/
    defaults: { _controller: KikalaFrontBundle:Default:legal }

kikala_front_about:
    path:     /about/
    defaults: { _controller: KikalaFrontBundle:Default:about }

kikala_front_register:
    path:     /register/
    defaults: { _controller: KikalaFrontBundle:User:register }

kikala_front_login:
    path:     /login/
    defaults: { _controller: KikalaFrontBundle:User:login }


kikala_front_forgot:
    path:     /forgot/
    defaults: { _controller: KikalaFrontBundle:User:forgot }


kikala_front_newPass:
    path:     /forgot/{token}/{email}
    defaults: { _controller: KikalaFrontBundle:User:newpass }


kikala_front_redirect:
    path:     /redirect/
    defaults: { _controller: KikalaFrontBundle:User:redirect }
    requirements:
         _method:  GET

kikala_front_lsForma:
    path:     /lsForma/{page}
    defaults: { _controller: KikalaFrontBundle:Formation:lsForma, page:1 }


logout:
    path:     /logout


kikala_front_formaDetail:
    path:     /formaDetail/{id}
    defaults: { _controller: KikalaFrontBundle:Formation:formaDetail }

kikala_front_kikoDetail:
    path:     /kikoDetail/{id}
    defaults: { _controller: KikalaFrontBundle:User:kikoDetail }

kikala_front_kikologue:
    path:     /kikologue/
    defaults: { _controller: KikalaFrontBundle:User:kikologue }


kikala_front_profil:
    path:     /profil/
    defaults: { _controller: KikalaFrontBundle:User:profil }

kikala_front_formaCreate:
    path:     /formaCreate/
    defaults: { _controller: KikalaFrontBundle:User:formaCreate }

kikala_front_myForma:
    path:     /myForma/
    defaults: { _controller: KikalaFrontBundle:User:myForma }

kikala_front_mesInscriptions:
    path:     /mesInscriptions/
    defaults: { _controller: KikalaFrontBundle:User:mesInscriptions }

kikala_front_tagCreate:
    path:     /tagCreate/
    defaults: { _controller: KikalaFrontBundle:User:tagCreate }

kikala_front_formaIns:
    path:     /formaIns/{id}
    defaults: { _controller: KikalaFrontBundle:Formation:formaIns }

kikala_front_formAnnul:
    path:     /formAnnul/{id}
    defaults: { _controller: KikalaFrontBundle:User:formAnnul }
