kikala_front_homepage:
    path:     /home/
    defaults: { _controller: KikalaFrontBundle:Default:home }

kikala_front_legal:
    path:     /legal/
    defaults: { _controller: KikalaFrontBundle:Default:legal }

kikala_front_about:
    path:     /about/
    defaults: { _controller: KikalaFrontBundle:Default:about }

kikala_front_register:
    path:     /register/
    defaults: { _controller: KikalaFrontBundle:User:register }

kikala_front_login:
    path:     /login/
    defaults: { _controller: KikalaFrontBundle:User:login }

kikala_front_forgot:
    path:     /forgot/
    defaults: { _controller: KikalaFrontBundle:User:forgot }


kikala_front_logout:
    path:     /logout/
    defaults: { _controller: KikalaFrontBundle:User:logout }

kikala_front_lsFoma:
    path:     /lsFoma/
    defaults: { _controller: KikalaFrontBundle:Formation:lsFoma }


kikala_front_formaDetail:
    path:     /formaDetail/
    defaults: { _controller: KikalaFrontBundle:Formation:formaDetail }

kikala_front_kikoDetail:
    path:     /kikoDetail/
    defaults: { _controller: KikalaFrontBundle:User:kikoDetail }

kikala_front_kikologue:
    path:     /kikologue/
    defaults: { _controller: KikalaFrontBundle:User:kikologue }

kikala_front_profil:
    path:     /profil/
    defaults: { _controller: KikalaFrontBundle:User:profil }

kikala_front_formaCreate:
    path:     /formaCreate/
    defaults: { _controller: KikalaFrontBundle:User:formaCreate }

kikala_front_myForma:
    path:     /myForma/
    defaults: { _controller: KikalaFrontBundle:User:myForma }

kikala_front_mes_inscriptions:
    path:     /mes_inscriptions/
    defaults: { _controller: KikalaFrontBundle:Default:mes_inscriptions }
