INSERT INTO category (name)
VALUES 
("Agriculture, Agroalimentaire"),
("Artisanat"),
("Audiovisuel, cinéma"),
("Automobile"),
("Banque, assurance"),
("Bâtiment, travaux publics"),
("Biologie, chimie, pharmacie"),
("Commerce, distribution"),
("Comptabilité, Secrétariat"),
("Création, métiers d'art"),
("Culture, patrimoine"),
("Défense, sécurité"),
("Droit"),
("Edition, livre"),
("Environnement"),
("Hôtellerie, restauration"),
("Immobilier"),
("Informatique, télécoms, Web"),
("Journalisme"),
("Langues"),
("Marketing, publicité"),
("Médical"),
("Mode, textile"),
("Psychologie"),
("Ressources humaines"),
("Spectacle, Métiers de la scène"),
("Sport"),
("Tourisme")