<?php

namespace Kikala\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionFormRepository extends EntityRepository
{
	public function countInscriptionForm($formation){		

			$count=$this->createQueryBuilder('i')
				->select('COUNT(i.id)')
				->where ('i.formation = :formation ')
				->setParameter('formation', $formation)
				->getQuery()
				->getSingleScalarResult();
				return $count;
	}


	public function getListInsByUser($user){
        $query = $this->createQueryBuilder('inscriptions')
            ->select('inscriptions', 'formation')
            ->where ('inscriptions.user = :user')
            ->leftJoin ('inscriptions.formation', 'formation')
            ->setParameter	('user', $user)
        	->getQuery();
        $mesformations=$query->getResult();
        return $mesformations;
    }

	public function cancelInsByUser($user, $formation){
        $query = $this->createQueryBuilder('cancel')
            ->select('cancel', 'formation')
            ->where ('cancel.user = :user')
            ->setParameter	('user', $user)
            ->andWhere('cancel.formation = :formation')
            ->setParameter	('formation', $formation)
        	->getQuery();
        $mesformations=$query->getResult();
        return $mesformations;
    }

}
