<?php

namespace Kikala\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionFormRepository extends EntityRepository
{
	public function countInscriptionForm($formation){		

			$count=$this->createQueryBuilder('i')
				->select('COUNT(i.id)')
				->where ('i.formation = :formation ')
				->setParameter('formation', $formation)
				->getQuery()
				->getSingleScalarResult();
				return $count;
	}
}
