<?php

namespace Kikala\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionFormRepository extends EntityRepository
{
}
