<?php

namespace Kikala\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserKikologueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserKikologueRepository extends EntityRepository
{
	public function countUser(){
		$count=$this->createQueryBuilder('pseudo')
				->select('COUNT(pseudo)')
				->getQuery()
				->getSingleScalarResult();
				return $count;
	}
}
