<?php

namespace Kikala\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserKikologueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserKikologueRepository extends EntityRepository
{
}
